on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0', '8.1']
    name: PHP v${{ matrix.php }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: nanasess/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
      - name: Install Dependencies
        run: |
          rm -rf vendor
          composer install
      - name: Run tests
        run: composer run tests



